name: Update CDN version

on:
  workflow_dispatch:
    inputs:
      status:
        description: 'My Input Description'
        required: true

jobs:
  successful_status:
    if: ${{ github.event.inputs.status == 'successful' }}
    runs-on: ubuntu-latest
    steps:


      - name: Update version
        run: npm version patch


      - name: Commit & Push build
        uses: CasperWA/push-protected@v2
        with:
          token: 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 
          branch: ${{ github.head_ref || github.ref_name }}
          unprotect_reviews: true
          tags: false

      - name: Update version status
        run: echo "Status is successful"

  failed_status:
    if: ${{ github.event.inputs.status == 'failed' }}
    runs-on: ubuntu-latest
    steps:
      - name: Update version status
        run: echo "Status is failed"
