name: Update CDN version

on:
  workflow_dispatch:
    inputs:
      status:
        description: 'My Input Description'
        required: true

jobs:
  successful_status:
    if: ${{ github.event.inputs.status == 'successful' }}
    runs-on: ubuntu-latest
    steps:
      - name: Git Identity
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: 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
          
      - name: Checking out a repo ${{ github.repository }}
        uses: actions/checkout@v3
        with:
          token: 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
          fetch-depth: 0

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'
          
      - name: Update version
        run: npm version patch


      - name: Commit & Push build
        uses: CasperWA/push-protected@v2
        with:
          token: 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 
          branch: ${{ github.head_ref || github.ref_name }}
          unprotect_reviews: true
          tags: false

      - name: Update version status
        run: echo "Status is successful"

  failed_status:
    if: ${{ github.event.inputs.status == 'failed' }}
    runs-on: ubuntu-latest
    steps:
      - name: Update version status
        run: echo "Status is failed"
